config/routes.rb
ALLOW_DOTS ||= /[^\/]+(?=\.(html|json|ttl)\z)|[^\/]+/

Rails.application.routes.draw do
  mount Blacklight::Oembed::Engine, at: 'oembed'
  mount Spotlight::Engine, at: 'spotlight'
  resources :rights
  blacklight_for :catalog
  devise_for :users
  mount Hydra::Collections::Engine => '/'
  mount CurationConcerns::Engine, at: '/'
  resources :welcome, only: :index
  root to: 'welcome#index'
  iiif_for 'riiif/image', at: '/image-service'
  curation_concerns_collections
  curation_concerns_basic_routes
  curation_concerns_embargo_management
  resources :admin_sets, constraints: { id: ALLOW_DOTS } do
    member do
      get :confirm_delete
    end
  end

  resque_web_constraint = lambda do |request|
    current_user = request.env['warden'].user
    current_user.present? && current_user.respond_to?(:groups) && current_user.groups.include?('admin')
  end

  constraints resque_web_constraint do
    mount ResqueWeb::Engine => "/resque"
  end

  get 'collections/:id/allow_downloads' => 'collections#allow_downloads', as: :allow_downloads
  get 'collections/:id/prevent_downloads' => 'collections#prevent_downloads', as: :prevent_downloads
  get 'admin_sets/:id/allow_downloads' => 'admin_sets#allow_downloads', as: :admin_set_allow_downloads
  get 'admin_sets/:id/prevent_downloads' => 'admin_sets#prevent_downloads', as: :admin_set_prevent_downloads
end

app/controllers/rights_controller.rb
class RightsController < ApplicationController
  authorize_resource class: "Qa::LocalAuthorityEntry"
  before_action :set_right, only: [:show, :edit, :update, :destroy]

  # GET /rights
  # GET /rights.json
  def index
    authority = Qa::LocalAuthority.where(name: 'rights').first
    @rights = authority.local_authority_entries
  end

  # GET /rights/1
  # GET /rights/1.json
  def show
  end

  # GET /rights/new
  def new
    authority = Qa::LocalAuthority.where(name: 'rights').first
    @right = authority.local_authority_entries.new
  end

  # GET /rights/1/edit
  def edit
  end

  # POST /rights
  # POST /rights.json
  def create
    authority = Qa::LocalAuthority.where(name: 'rights').first
    @right = authority.local_authority_entries.new(right_params)

    respond_to do |format|
      if @right.save
        format.html { redirect_to rights_path, notice: 'Right was successfully created.' }
        format.json { render :show, status: :created, location: @right }
      else
        format.html { render :new }
        format.json { render json: @right.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rights/1
  # PATCH/PUT /rights/1.json
  def update
    respond_to do |format|
      if @right.update(right_params)
        format.html { redirect_to rights_path, notice: 'Right was successfully updated.' }
        format.json { render :show, status: :ok, location: @right }
      else
        format.html { render :edit }
        format.json { render json: @right.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rights/1
  # DELETE /rights/1.json
  def destroy
    @right.destroy
    respond_to do |format|
      format.html { redirect_to rights_path, notice: 'Right was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_right
      @right = Qa::LocalAuthorityEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def right_params
      params[:local_authority_entry].permit(:local_authority_id, :label, :uri)
    end
end

app/helpers/rights_helper.rb
module RightsHelper
end

app/views/rights/_form.html.erb
<% url = @right.id.nil? ? rights_path : right_path(@right) %>
<%= simple_form_for(@right, url: url, html: {class: "form-horizontal"}) do |f| %>
  <% if @right.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@right.errors.count, "error") %> prohibited this right from being saved:</h2>
      <ul>
      <% @right.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-sm-3">  
    <%= f.label :label, "Rights Statement Label"%>
  </div>
  <div class="col-sm-9">
    <%= f.input :label, label: false %>
  </div>
  <div class="col-sm-3">
    <%= f.label :uri, "URI" %>
  </div>
  <div class="col-sm-9">
    <%= f.input :uri, label: false, disabled: !f.object.uri_editable? %>
  </div>
  <div class="actions">
    <%= f.submit "Save", :class => 'btn btn-primary' %>&nbsp;
    <%= link_to 'Back', rights_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/rights/edit.html.erb
<h1 class="page-header">Edit Rights Statement</h1>

<%= render 'form' %>

app/views/rights/index.html.erb
<h1 class="page-header">Rights Statements</h1>

<table class="table table-condensed table-responsive">
  <thead>
    <tr>
      <th>Rights Statement Label</th>
      <th>URI</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @rights.each do |right| %>
      <tr>
        <td><%= right.label %></td>
        <td><%= right.uri %></td>
        <td><%= link_to 'Edit', edit_right_path(right), :class => "btn btn-xs btn-primary" %></td>
        <td><%= link_to 'Destroy', right_path(right), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-xs btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Rights Statement', new_right_path, :class => 'btn btn-primary' %>

app/views/rights/new.html.erb
<h1 class="page-header">New Rights Statement</h1>

<%= render 'form' %>